### ISSUE TITLE
Add-On Suggestions

### ISSUE THREAD

**Issue by LollaManolla** [Diwanee-FE/Diwanee-Boilerplate#21]
Add-ons to be considered for implementation. 
These add-ons should help us to improve sites (look, behaviour, coding)

**Content**

**matchHeight** makes the height of all selected elements exactly equal.
http://brm.io/jquery-match-height/

**Comment by IvanBuljovcic** [comment]
**matchHeight** will not be allowed on Webedia projects. I say this from past experience.. since it has to calculate element heights after loading assets, it has a visual _pop_ in the layout. Hence it is not allowed.
